-- Signal Blueprint - Add Daily Decks Table
-- Run this in your Supabase SQL Editor to add the daily_decks table
-- This is a standalone migration that can be run after 001_create_tables.sql

-- Daily Decks (organization-wide daily task decks generated by Questmaster)
CREATE TABLE IF NOT EXISTS daily_decks (
  id TEXT PRIMARY KEY, -- Format: daily-deck-{orgId}-{date}
  org_id TEXT NOT NULL,
  date TEXT NOT NULL, -- ISO date string (YYYY-MM-DD)
  generated_at TIMESTAMPTZ NOT NULL,
  job_run_id TEXT, -- Link to JobRunSummary that generated this deck
  items JSONB NOT NULL DEFAULT '[]', -- Array of deck items (task info)
  team_capacity JSONB NOT NULL DEFAULT '[]', -- Array of team capacity info
  summary JSONB NOT NULL DEFAULT '{}', -- Summary object (totalTasks, totalEstimatedMinutes, etc.)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_daily_decks_org FOREIGN KEY (org_id) REFERENCES orgs(id) ON DELETE CASCADE
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_daily_decks_org_id ON daily_decks(org_id);
CREATE INDEX IF NOT EXISTS idx_daily_decks_date ON daily_decks(date);
CREATE INDEX IF NOT EXISTS idx_daily_decks_org_date ON daily_decks(org_id, date);

-- Enable RLS
ALTER TABLE daily_decks ENABLE ROW LEVEL SECURITY;

-- RLS Policy
DROP POLICY IF EXISTS "Allow all for service role" ON daily_decks;
CREATE POLICY "Allow all for service role" ON daily_decks FOR ALL USING (true);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
DROP TRIGGER IF EXISTS update_daily_decks_updated_at ON daily_decks;
CREATE TRIGGER update_daily_decks_updated_at BEFORE UPDATE ON daily_decks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

